intent_mapping = {
    "ordercoffee.ordercoffee-yes": [0, 1, 2, 3, 4, 13],
    "orderdrink.orderdrink-yes": [0, 5, 6, 7, 8, 13],
    "ordergourmet.ordergourmet-yes": [0, 9, 10, 11, 13]
}
key_mapping = {1: "coffee",
               2: "size",
               3: "strength",
               5: "drink",
               6: "size",
               7: "strength",
               9: "gourmet",
               10: "strength"}

button_mapping = {1: {"Roaster's Blend": 4,
                      "Rainbow's End": 5,
                      "Evening Fantasy": 6,
                      "Coffee 50-50": 7,
                      "Hot Water": 8},
                  2: {"small": 10,
                      "medium": 11,
                      "large": 12},
                  3: {"mild": 16,
                      "regular": 17,
                      "strong": 18},
                  5: {"French Vanilla": 22,
                      "French Vanilla Coffee": 23,
                      "Vanilla Moka": 24,
                      "Hot Chocolate": 25,
                      "Mokaccino": 26,
                      "Vanilla Moka Coffee": 27,
                      "Choco Latte": 28,
                      "Hot Water": 29
                      },
                  6: {"small": 31,
                      "medium": 32,
                      "large": 33},
                  7: {"mild": 35,
                      "regular": 36,
                      "strong": 37},
                  9: {"Chocolate Vanilla Latte": 41,
                      "Energy Shot": 42,
                      "Hot Shot Blend": 43,
                      "Long Espresso": 44,
                      "Cafe Latte": 45,
                      "Cappuccino": 46,
                      "Hot Water": 47},
                  10: {"mild": 50,
                      "regular": 51,
                      "strong": 52},
                  }
